service: viewspots

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  viewspots:
    handler: handler.viewspots
    events:
    - httpApi:
        path: /
        method: post

plugins:
  - serverless-offline